version: '2'

services:
  nginx:
    build: ./nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx-ssl/conf.d:/etc/nginx/conf.d
#      - ./nginx-ssl/dhparam.pem:/etc/nginx/dhparam.pem
#      - ./nginx-ssl/include:/etc/nginx/include
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certs:/etc/certs

  gogs:
    image: gogs/gogs
    ports:
      - "2222:22"
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data/gogs:/data

  mysql:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
